# Default values for pacman-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
pacman:
  replicaCount: 1
  image:
    registry: ghcr.io
    repository: shuguet
    image: pacman
    tag: latest
    pullPolicy: Always

mongo:
  storage: 1Gi
  # Use plain text data, helm will encode in base64
  databaseName: 'pacman'
  databasePassword: ''
  databaseUser: ''
  # FIXME: Add support for this
  # deploymentType: 'deployment' # or: 'statefulset'
  image:
    registry: ghcr.io
    repository: shuguet
    image: mongo
    tag: latest
    pullPolicy: Always

## Service configuration.
service:
  type: ClusterIP
  port: 80

## Ingress configuration.
ingress:
  create: false
  class: ""
  host: ""
  path: ""
  pathType: ""
  annotations: {}
  tls:
    enabled: false

## Red Hat OpenShift Route configuration.
route:
  create: false
  host: ""
  path: ""
  annotations: {}
    # kubernetes.io/tls-acme: "true"
    # haproxy.router.openshift.io/disable_cookies: "true"
    # haproxy.router.openshift.io/balance: roundrobin
  labels: {}
    # key: value
  tls:
    enabled: false
    insecureEdgeTerminationPolicy: "Redirect" # What to do in case of an insecure traffic edge termination
    termination: "edge" # Where this TLS configuration should terminate

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

rbac:
  create: true

psp:
  create: false # Deprecated in 1.21+, unavailable in 1.25+

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80